kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    spring.cloud.kubernetes.config.informer.enabled: 'true'
data:
  test-live-secrets-k8s.yaml: |-
    test-live-secrets-k8s:
      test-configmap-property: {{ .Values.secrets.someSecret }}
  test-live-secrets-k8s.properties: |-
    message=from cm default
    threshold=100